version: 2.1

# Resources defined in this config have a prefix `B-` to avoid conflicts upon combine/merge

jobs:
  B-test:
    docker:
      - image: debian:unstable-slim
    steps:
      - run: echo Running tests for subdirectory B

workflows:
  B-main-workflow:
    jobs:
      - shared-job
      - B-test:
          requires:
            - shared-job
